name: Build and Deploy
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true
jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20.8.0
          cache: 'npm'
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3.0.6
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: "./dist"
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1.2.9
            
